const STAFF=[{code:"14051200",name:"حسین کریمی",title:"مدیر عملیات بین‌بانکی"},{code:"14051201",name:"مریم رضایی",title:"کارشناس رفع مسدودی"},{code:"14051202",name:"علی محمدی",title:"کارشناس مغایرت و تراکنش"}];
const NEWS_POOL=[[{title:"آمادگی بانک مرکزی برای عرضه ارز تا دو میلیارد دلار",kicker:"رئیس‌کل بانک مرکزی:"},{title:"موسسات اعتباری پیشرو در نظارت شرعی معرفی شدند",kicker:"دبیر شورای فقهی:"},{title:"شبکه بانکی در خط مقدم جنگ ترکیبی است",kicker:"مشاور رئیس کل:"}],[{title:"نرخ حواله و اسکناس مرکز مبادله به‌روزرسانی شد",kicker:"اداره عملیات ارزی:"},{title:"دستورالعمل رفع مسدودی حساب‌های مالیاتی ابلاغ شد",kicker:"اداره اطلاعات بانکی:"},{title:"پایا و ساتنا بدون اختلال اعلام شد",kicker:"شرکت ملی خدمات انفورماتیک:"}],[{title:"تخصیص ارز دارو و کالاهای اساسی ادامه دارد",kicker:"معاون ارزی:"},{title:"گزارش ماهانه نقدینگی منتشر شد",kicker:"اداره بررسی‌ها:"},{title:"نشست مدیران نظارت برگزار شد",kicker:"حوزه نظارت:"}],[{title:"عرضه اوراق گواهی سپرده اعلام شد",kicker:"عملیات بازار باز:"},{title:"سامانه استعلام مسدودی به‌روزرسانی شد",kicker:"میز خدمت:"},{title:"همایش سیاست پولی فردا برگزار می‌شود",kicker:"روابط عمومی:"}]];
const EVENTS_POOL=[[{title:"نشست بانک مرکزی و سازمان مالیاتی",place:"میرداماد",when:"امروز"},{title:"کارگاه رفع مسدودی",place:"سالن همایش",when:"فردا"},{title:"روادید ارزی زیارت و درمان",place:"مرکز مبادله",when:"این هفته"}],[{title:"جلسه شورای فقهی",place:"ساختمان مرکزی",when:"امروز"},{title:"نسخه جدید ساتنا",place:"خدمات انفورماتیک",when:"این هفته"},{title:"روادید ارزی دانشجویی",place:"اداره ارزی",when:"تا پایان ماه"}],[{title:"بازدید نظارت از بانک‌های استان مرکزی",place:"اراک",when:"امروز"},{title:"میز خدمت رفع مسدودی مالیاتی",place:"پایگاه اطلاع‌رسانی",when:"همه‌روزه"},{title:"روادید حج و عمره",place:"مرکز مبادله",when:"۶ ساعته"}],[{title:"همایش بانکداری اسلامی",place:"تالار همایش",when:"امروز"},{title:"کارگروه شبا پایا ساتنا",place:"نظام‌های پرداخت",when:"فردا"},{title:"روادید مأموریت و درمان",place:"شعبه ارزی",when:"این هفته"}]];
const VISA_POOL=[[{item:"روادید زیارتی",rate:"۴۲٬۰۰۰"},{item:"روادید دانشجویی",rate:"۴۳٬۲۰۰"},{item:"روادید درمانی",rate:"۴۲٬۸۰۰"}],[{item:"روادید زیارتی",rate:"۴۲٬۱۵۰"},{item:"روادید دانشجویی",rate:"۴۳٬۳۵۰"},{item:"روادید درمانی",rate:"۴۲٬۹۰۰"}],[{item:"روادید زیارتی",rate:"۴۱٬۹۵۰"},{item:"روادید دانشجویی",rate:"۴۳٬۱۰۰"},{item:"روادید درمانی",rate:"۴۲٬۷۰۰"}],[{item:"روادید زیارتی",rate:"۴۲٬۳۰۰"},{item:"روادید دانشجویی",rate:"۴۳٬۴۸۰"},{item:"روادید درمانی",rate:"۴۳٬۰۰۰"}]];
const WEEKDAYS=["یکشنبه","دوشنبه","سه‌شنبه","چهارشنبه","پنجشنبه","جمعه","شنبه"];
const MONTHS=["فروردین","اردیبهشت","خرداد","تیر","مرداد","شهریور","مهر","آبان","آذر","دی","بهمن","اسفند"];
function toJalali(gy,gm,gd){const g=[0,31,59,90,120,151,181,212,243,273,304,334];let gy2=gm>2?gy+1:gy;let days=355666+365*gy+Math.floor((gy2+3)/4)-Math.floor((gy2+99)/100)+Math.floor((gy2+399)/400)+gd+g[gm-1];let jy=-1595+33*Math.floor(days/12053);days%=12053;jy+=4*Math.floor(days/1461);days%=1461;if(days>365){jy+=Math.floor((days-1)/365);days=(days-1)%365}const jm=days<186?1+Math.floor(days/31):7+Math.floor((days-186)/30);const jd=1+(days<186?days%31:(days-186)%30);return{jy,jm,jd}}
function pad(n){return String(n).padStart(2,"0")}
function fa(s){return String(s).replace(/[0-9]/g,d=>"۰۱۲۳۴۵۶۷۸۹"[d])}
function nowInfo(){const d=new Date();const j=toJalali(d.getFullYear(),d.getMonth()+1,d.getDate());const slot=Math.floor(d.getTime()/(6*3600*1000));const ws=Math.floor(d.getHours()/6)*6;return{slot,weekday:WEEKDAYS[d.getDay()],dateFa:fa(j.jy+"/"+pad(j.jm)+"/"+pad(j.jd)),dateLong:WEEKDAYS[d.getDay()]+" "+fa(j.jd)+" "+MONTHS[j.jm-1]+" "+fa(j.jy),timeFa:fa(pad(d.getHours())+":"+pad(d.getMinutes())),window:fa(pad(ws)+":00")+" تا "+fa(pad((ws+6)%24)+":00")}}
function liveNews(){const info=nowInfo();return NEWS_POOL[info.slot%4].map((n,i)=>Object.assign({},n,{date:info.dateFa}))}
function liveEvents(){return EVENTS_POOL[nowInfo().slot%4]}
function liveVisa(){return VISA_POOL[nowInfo().slot%4]}
const CASE={name:"مریم جعفری",nid:"۰۵۳۲۵۹۱۰۰۲",bank:"بانک ملت",acc:"۹۹۸۷۰۴۵۶۳۰۱",amount:"۷۴۹٬۸۶۵٬۷۹۰٬۴۳۲ ریال",track:"RMS-1405-10089",date:"۲۱ مرداد ۱۴۰۵",status:"در حال بررسی رفع مسدودی"};
let session=null,slide=0,view="home";
function go(v){document.getElementById("menu").classList.remove("open");if(["dash","unblocks","inq","case","process"].includes(v)&&!session){view="login";render();return}view=v;render();window.scrollTo(0,0)}
function pages(){
const info=nowInfo();
if(view==="home"){const news=liveNews();const n=news[slide%3];const ev=liveEvents();const visa=liveVisa();
return `<div class=\"hero\"><div class=\"rel\"><div style=\"height:210px;background:linear-gradient(160deg,#2a3a4a,#6a5a4a);display:grid;place-items:center;text-align:center;padding:12px\">تالار همایش بانک مرکزی<br>${info.dateLong}</div><div class=\"date-badge\"><span>■</span> ${info.dateFa} · ${info.timeFa}</div></div><div class=\"hero-cap\">${n.title}</div></div>
<div class=\"news wrap\"><div class=\"tag\">آخرین خبرها</div><div style=\"height:36px\"></div><div class=\"row\" style=\"background:#f7f3ea;font-size:13px\">به‌روزرسانی هر ۶ ساعت · پنجره ${info.window}</div>${news.map(x=>`<div class=\"row\"><div class=\"kicker\">${x.kicker}</div><p>${x.title}</p></div>`).join(\"\")}</div>
<div class=\"news wrap\" style=\"margin-top:12px\"><div class=\"tag\">رویدادها و روادید</div><div style=\"height:36px\"></div>${ev.map(x=>`<div class=\"row\"><div class=\"kicker\">${x.when} · ${x.place}</div><p>${x.title}</p></div>`).join(\"\")}<div class=\"row\"><div class=\"kicker\">نرخ روادید ارزی</div>${visa.map(v=>`<p>${v.item}: ${v.rate} تومان</p>`).join(\"\")}</div></div>`}
if(view==="login"){return `<div class=\"page wrap\"><div class=\"card\"><h2>میز خدمت کارکنان</h2><form id=\"loginForm\"><label>کد پرسنلی</label><input name=\"code\" placeholder=\"14051201\"/><label>رمز عبور</label><input name=\"pass\" type=\"password\" placeholder=\"123456\"/><p id=\"err\" style=\"color:var(--danger)\"></p><button class=\"btn\" type=\"submit\">ورود به سامانه</button></form>${STAFF.map(s=>`<button class=\"demo\" data-demo=\"${s.code}\"><span>${s.name}</span><span>${s.code}</span></button>`).join(\"\")}</div></div>`}
if(view==="dash"){return `<div class=\"page wrap\"><div class=\"card\"><h2>سلام، ${session.name}</h2><p><b data-go=\"case\">${CASE.name}</b> — ${CASE.track} — <span class=\"badge\">${CASE.status}</span></p></div><div class=\"card\"><button class=\"btn\" data-go=\"process\">بررسی فرآیند رفع مسدودی حساب</button></div></div>`}
if(view==="unblocks"||view==="case"){return `<div class=\"page wrap\"><div class=\"card\"><h2>${CASE.name}</h2><div class=\"grid\"><div>کد ملی: ${CASE.nid}</div><div>${CASE.bank} ${CASE.acc}</div><div>مسدود: ${CASE.amount}</div><div>پرداخت مالیات: ۳۱٬۳۷۰٬۰۹۸٬۴۸۰ ریال — ۱۴۰۵/۰۵/۲۵</div></div></div><div class=\"card\"><button class=\"btn\" data-go=\"process\">بررسی فرآیند</button></div></div>`}
if(view==="process"){return `<div class=\"page wrap\"><div class=\"card\"><h2>بررسی فرآیند رفع مسدودی حساب</h2><p>${CASE.track} — ${CASE.name}</p><span class=\"badge\">${CASE.status}</span></div><div class=\"card\"><div class=\"step done\"><b>۱. دستور قضایی مسدودی</b><span>۱۸ و ۲۰ مرداد</span></div><div class=\"step done\"><b>۲. ابلاغ بانک مرکزی به ملت</b><span>۲۱ مرداد</span></div><div class=\"step done\"><b>۳. پرداخت مالیات ۳۱٬۳۷۰٬۰۹۸٬۴۸۰ ریال</b><span>۲۵ مرداد</span></div><div class=\"step now\"><b>۴. درخواست رفع مسدودی مالیات به بانک مرکزی</b><span>۲۵ مرداد</span></div><div class=\"step\"><b>۵. کنترل کارشناسی</b><span>در انتظار تأیید</span></div><div class=\"step\"><b>۶. ابلاغ رفع به بانک ملت</b><span>پس از تأیید</span></div></div><div class=\"card\"><button class=\"btn ok\" id=\"approveUnblock\">تأیید و صدور دستور رفع مسدودی</button><div id=\"procMsg\"></div></div></div>`}
if(view==="inq"){return `<div class=\"page wrap\"><div class=\"card\"><h2>استعلام مسدودی</h2><label>کد ملی</label><input id=\"nid\" placeholder=\"0532591002\"/><button class=\"btn\" id=\"doInq\">استعلام</button><div id=\"inqOut\"></div></div></div>`}
return ""}
function bind(){document.querySelectorAll("[data-go]").forEach(el=>el.onclick=e=>{e.preventDefault();go(el.getAttribute("data-go"))});document.querySelectorAll("[data-demo]").forEach(el=>el.onclick=()=>{session=STAFF.find(x=>x.code===el.getAttribute("data-demo"));go("dash")});const form=document.getElementById("loginForm");if(form)form.onsubmit=e=>{e.preventDefault();const s=STAFF.find(x=>x.code===form.code.value.replace(/\\D/g,""));if(!s||form.pass.value!=="123456"){document.getElementById("err").textContent="کد یا رمز نادرست است";return}session=s;go("dash")};const ap=document.getElementById("approveUnblock");if(ap)ap.onclick=()=>{CASE.status="دستور رفع مسدودی صادر شد";document.getElementById("procMsg").textContent="دستور رفع برای بانک ملت ثبت شد."};const doInq=document.getElementById("doInq");if(doInq)doInq.onclick=()=>{const v=(document.getElementById("nid").value||"").replace(/\\D/g,"");document.getElementById("inqOut").innerHTML=(v==="0532591002"||!v)?`<p>${CASE.name} — ${CASE.status}</p><a data-go=\"case\">پرونده</a>`:"موردی یافت نشد";bind()}}
function render(){document.getElementById("app").innerHTML=pages();const bar=document.getElementById("staffbar");if(session){bar.classList.remove("hidden");document.getElementById("who").textContent=session.name;document.getElementById("deskLink").textContent="داشبورد";document.getElementById("deskLink").setAttribute("data-go","dash")}else{bar.classList.add("hidden");document.getElementById("deskLink").textContent="میز خدمت بانک مرکزی";document.getElementById("deskLink").setAttribute("data-go","login")}bind()}
document.getElementById("menuBtn").onclick=()=>document.getElementById("menu").classList.toggle("open");
document.getElementById("logout").onclick=()=>{session=null;go("home")};
document.getElementById("q").onkeydown=e=>{if(e.key==="Enter"){e.preventDefault();go(session?"inq":"login")}};
setInterval(()=>{if(view==="home"){slide=(slide+1)%3;render()}},6000);
setInterval(()=>{if(view==="home")render()},60000);
render();
